name: task-dyva
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pandas=1.1.*
  - numpy=1.20.*
  - pytorch=1.8.*
  - scipy=1.6.*
  - seaborn=0.11.*
  - PyYAML=5.4.*
  - scikit-learn=0.24.*
  - neptune-client=0.16.*
  - dill=0.3.*
  - pytest=7.1.*
  - tensorboard=2.9.*
  - jsonschema=3.*
